### PR TITLE
Feature/v0.0.8

### PR DESCRIPTION
**Pull request by ravi-databricks**
## [v.0.0.8] 
- Added dlt append_flow api support: [PR](https://github.com/databrickslabs/dlt-meta/pull/58)
- Added dlt append_flow api support for silver layer: [PR](https://github.com/databrickslabs/dlt-meta/pull/63)
- Added support for file metadata columns for autoloader: [PR](https://github.com/databrickslabs/dlt-meta/pull/56)
- Added support for Bring your own custom transformation: [Issue](https://github.com/databrickslabs/dlt-meta/issues/68)
- Added support to Unify PyPI releases with GitHub OIDC: [PR](https://github.com/databrickslabs/dlt-meta/pull/62)
- Added demo for append_flow and file_metadata options: [PR](https://github.com/databrickslabs/dlt-meta/issues/74)
- Added Demo for silver fanout architecture: [PR](https://github.com/databrickslabs/dlt-meta/pull/83)
- Added documentation in docs site for new features: [PR](https://github.com/databrickslabs/dlt-meta/pull/64)
- Added unit tests to showcase silver layer fanout examples: [PR](https://github.com/databrickslabs/dlt-meta/pull/67)
- Fixed issue for No such file or directory: '/demo' :[PR](https://github.com/databrickslabs/dlt-meta/issues/59)
- Fixed issue DLT-META CLI onboard command issue for Azure: databricks.sdk.errors.platform.ResourceAlreadyExists :[PR](https://github.com/databrickslabs/dlt-meta/issues/51)
- Fixed issue Changed dbfs.create to mkdirs for CLI: [PR](https://github.com/databrickslabs/dlt-meta/pull/53)
- Fixed issue DLT-META CLI should use pypi lib instead of whl : [PR](https://github.com/databrickslabs/dlt-meta/pull/79)

### CODE REVIEW

**Review by brij-raghuwanshi-db — APPROVED** [review]
Approved.

**Review by neil90 — APPROVED** [review]
LGTM, GJ Ravi!

**Review by brij-raghuwanshi-db — APPROVED** [review]
Approved

**Review by brij-raghuwanshi-db — APPROVED** [review]
Approved.

**Review by brij-raghuwanshi-db — APPROVED** [review]
Submitting Approve.

**Review by brij-raghuwanshi-db — APPROVED** [review]
Approved.

**Review by brij-raghuwanshi-db — APPROVED** [review]
Approved with write access.

**Review by ganeshchand — APPROVED** [review]
LGTM

**Review by alexott — APPROVED** [review]

**Comment by pohlposition** [comment]
LGTM

**Review by pohlposition — APPROVED** [review]
LGTM

**Review by pohlposition — APPROVED** [review]
LGTM
Approved
Ship It
Launch

**Pull request merged**
